---
name: admintweaks-dev-controllers
---
SilverStripe\Dev\DevelopmentAdmin:
  registered_controllers:
    admintweaks-icons:
      controller: Restruct\Silverstripe\AdminTweaks\Dev\IconsPreviewController
      links:
        admintweaks-icons: 'Browse curated Bootstrap Icons for admin UI'
