---
name: admintweaks-routes
after:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'dev/admintweaks-icons': 'Restruct\Silverstripe\AdminTweaks\Dev\IconsPreviewController'
